version: '3'
services:
  mysql:
    build: .
    ports:
      - "3314:3306"
    environment:
      - MYSQL_DATABASE=board_db
      - MYSQL_USER=springuser
      - MYSQL_PASSWORD=ThePassword
      - MYSQL_ROOT_PASSWORD=TestRootPassword
    volumes:
      - ./mysql/config/my.cnf:/etc/mysql/conf.d/my.cnf